name: ESP-Matter Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up ESP-IDF
        uses: espressif/setup-esp-idf@v1.3.3
        with:
          version: latest

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y ninja-build ccache libffi-dev libssl-dev cmake python3-pip python3-setuptools python3-serial
          python3 -m pip install --upgrade pip
          pip install -r $IDF_PATH/requirements.txt

      - name: Configure ESP-IDF Target
        run: |
          . $IDF_PATH/export.sh
          idf.py set-target esp32c6  # Change target if needed

      - name: Build ESP-Matter Light Example
        run: |
          . $IDF_PATH/export.sh
          idf.py build
