name: ESP-Matter Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git wget flex bison gperf python3 python3-pip python3-setuptools \
              python3-serial python3-cryptography python3-future python3-pyparsing ninja-build \
              cmake ccache libffi-dev libssl-dev

      - name: Clone ESP-IDF
        run: |
          git clone --recursive https://github.com/espressif/esp-idf.git ~/esp-idf
          cd ~/esp-idf
          git checkout v5.1  # Change this to match your ESP-IDF version
          ./install.sh

      - name: Clone ESP-Matter
        run: |
          git clone --recursive https://github.com/espressif/esp-matter.git ~/esp-matter
          cd ~/esp-matter
          git checkout v1.0  # Change this based on the ESP-Matter version you're using

      - name: Set Environment Variables
        run: |
          echo "export IDF_PATH=~/esp-idf" >> $GITHUB_ENV
          echo "export ESP_MATTER_PATH=~/esp-matter" >> $GITHUB_ENV
          echo "export PATH=$IDF_PATH/tools:$PATH" >> $GITHUB_ENV

      - name: Build ESP-Matter Light Example
        run: |
          . ~/esp-idf/export.sh
          idf.py set-target esp32c6  # Change the target as needed
          idf.py build
