name: ESP-Matter Light Example Build (ESP32C6 Thread)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Debug Repository Structure
        run: ls -R  # Print directory structure for debugging

      - name: Set up ESP-IDF
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip git wget flex bison gperf cmake ninja-build ccache libffi-dev libssl-dev dfu-util
          git clone --recursive https://github.com/espressif/esp-idf.git ~/esp-idf
          cd ~/esp-idf
          git checkout v5.1
          ./install.sh
          echo "source ~/esp-idf/export.sh" >> ~/.bashrc
          source ~/esp-idf/export.sh

      - name: Set up ESP-Matter
        run: |
          cd $GITHUB_WORKSPACE
          git submodule update --init --recursive

      - name: Configure for ESP32C6 Thread
        run: |
          cd $GITHUB_WORKSPACE  # Since "light" is the repo, we stay in root
          
          if [ -f "sdkconfig.esp32c6.thread" ]; then
            cp sdkconfig.esp32c6.thread sdkconfig
          elif [ -f "sdkconfig.defaults.esp32c6_thread" ]; then 
            cp sdkconfig.defaults.esp32c6_thread sdkconfig
          else
            echo "Error: Neither sdkconfig.esp32c6.thread nor sdkconfig.defaults.esp32c6_thread found!"
            exit 1
          fi
          
          source ~/esp-idf/export.sh
          idf.py reconfigure

      - name: Build the Project
        run: |
          cd $GITHUB_WORKSPACE
          source ~/esp-idf/export.sh
          idf.py build

      - name: Upload Firmware Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: esp32c6-thread-light-firmware
          path: build/*.bin
