name: ESP-Matter Light Example Build (ESP32C6 Thread)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Debug Repository Structure
        run: |
          echo "Current Directory: $(pwd)"
          echo "Listing Files:"
          ls -R  # Debug all files

      - name: Set up ESP-IDF
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip git wget flex bison gperf cmake ninja-build ccache libffi-dev libssl-dev dfu-util
          
          # Force Python 3.10 (to avoid issues with 3.12)
          sudo apt install -y python3.10 python3.10-venv python3.10-dev
          sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.10 1
          
          git clone --recursive https://github.com/espressif/esp-idf.git ~/esp-idf
          cd ~/esp-idf
          git checkout v5.1
          ./install.sh
          echo "source ~/esp-idf/export.sh" >> ~/.bashrc
          source ~/esp-idf/export.sh

      - name: Set up ESP-Matter
        run: |
          cd $GITHUB_WORKSPACE
          git submodule update --init --recursive

      - name: Configure for ESP32C6 Thread
        run: |
          echo "Checking for sdkconfig files..."
          find . -name "sdkconfig.esp32c6.thread" -o -name "sdkconfig.defaults.c6_thread"

          SDKCONFIG_PATH=$(find . -name "sdkconfig.esp32c6.thread" | head -n 1)
          if [ -z "$SDKCONFIG_PATH" ]; then
            SDKCONFIG_PATH=$(find . -name "sdkconfig.defaults.c6_thread" | head -n 1)
          fi

          if [ -z "$SDKCONFIG_PATH" ]; then
            echo "❌ Error: Neither sdkconfig.esp32c6.thread nor sdkconfig.defaults.c6_thread found!"
            exit 1
          fi

          echo "✅ Found sdkconfig at: $SDKCONFIG_PATH"
          cp "$SDKCONFIG_PATH" sdkconfig
          
          source ~/esp-idf/export.sh
          idf.py reconfigure

      - name: Debug CMake Configuration
        run: |
          echo "Running CMake manually to check errors..."
          cd $GITHUB_WORKSPACE
          source ~/esp-idf/export.sh
          cmake -G Ninja -DPYTHON=$(which python3) -DESP_PLATFORM=1 -DCCACHE_ENABLE=0 .
      
      - name: Build the Project
        run: |
          cd $GITHUB_WORKSPACE
          source ~/esp-idf/export.sh
          idf.py build || (echo "🔥 Build failed! Check logs in build/log/" && exit 1)

      - name: Upload Firmware Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: esp32c6-thread-light-firmware
          path: build/*.bin
